steps:
  # Run the Maven build
  - name: maven:3.6.0-jdk-11
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/tenant-registration-ms', '.']
  # Run the Maven build x
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
      - run
      - --image=gcr.io/${PROJECT_ID}/tenant-registration-ms:latest
      - --location=us-central1-c
      - --cluster=tenant-registration-ms
      - --expose=8080
images: ['gcr.io/$PROJECT_ID/tenant-registration-ms']